import {
  ArrowDown,
  Bird,
  Box,
  BrushCleaning,
  Camera,
  Car,
  CarFront,
  Cloud,
  CloudFog,
  CloudRain,
  Flower2,
  Focus,
  HardHat,
  Home,
  House,
  Image as ImageIcon,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  Maximize2,
  Moon,
  MoveHorizontal,
  PawPrint,
  PenLine,
  Pencil,
  PersonStanding,
  Plane,
  Rotate3d,
  Ruler,
  ScanSearch,
  Snowflake,
  Sparkles,
  Sprout,
  Sun,
  SunDim,
  Sunrise,
  Sunset,
  Trees,
  Users,
  Video,
  WandSparkles,
  ZoomIn,
  ZoomOut,
  Clock,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  box: Box,
  image: ImageIcon,
  video: Video,
  "wand-sparkles": WandSparkles,
  "maximize-2": Maximize2,
  sparkles: Sparkles,
  sun: Sun,
  "sun-dim": SunDim,
  snowflake: Snowflake,
  leaf: Leaf,
  ruler: Ruler,
  "pen-line": PenLine,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  clock: Clock,
  "rotate-3d": Rotate3d,
  cloud: Cloud,
  camera: Camera,
  moon: Moon,
  "cloud-rain": CloudRain,
  "scan-search": ScanSearch,
  users: Users,
  focus: Focus,
  "paw-print": PawPrint,
  "layout-grid": LayoutGrid,
  "layout-template": LayoutTemplate,
  "brush-cleaning": BrushCleaning,
  house: House,
  plane: Plane,
  "hard-hat": HardHat,
  lightbulb: Lightbulb,
  sunrise: Sunrise,
  sunset: Sunset,
  "person-standing": PersonStanding,
  car: Car,
  "car-front": CarFront,
  "cloud-fog": CloudFog,
  bird: Bird,
  "flower-2": Flower2,
  sprout: Sprout,
  trees: Trees,
  home: Home,
  pencil: Pencil,
  "move-horizontal": MoveHorizontal,
  "arrow-down": ArrowDown,
};

export function getCatalogIcon(name?: string): LucideIcon {
  if (!name) return Sparkles;
  return ICONS[name] ?? Sparkles;
}
